### ISSUE TITLE
question about your Git actions

### ISSUE THREAD

**Issue by brokedba** [DhruvinSoni30/Terraform_multiple_modules#1]
would you mind explain how did you get that done through git actions ?
 I saw workflows/*yaml  files that were supposed to be used to carry on the actions but would you explain these particular steps.
also , I thought in CI/CD pipelines you can define the credentials or anything sensitive in the specific section in github actions page .
I see no print screen of those steps , it would nice to see more of it.
 cheers

**Comment by DhruvinSoni30** [comment]
Sure!

1. There are 3 .yaml files for all 3 different environments i.e dev, stg & prod For ex. If I do commit in stg environment then the stg.yaml action file will trigger and start the action. This is exact same for dev & prod 
2. I stored my credentials in environment section of the repository as the secrets, github has the default feature it will fetch the secret from there .

I hope this will clarify your doubts! Please let me know if you need help with anything else!

**Comment by DhruvinSoni30** [comment]
Closing the issue, please create another one if you have any other doubts
